# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Aug 31 12:12:25 2011
#      by: pyside-uic 0.2.13 running on PySide 1.0.6
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 602)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.render_area = RenderArea(self.groupBox)
        self.render_area.setMinimumSize(QtCore.QSize(525, 475))
        self.render_area.setStyleSheet("background: rgb(0, 0, 0);")
        self.render_area.setObjectName("render_area")
        self.verticalLayout_2.addWidget(self.render_area)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toggle_simulation = QtGui.QPushButton(self.groupBox)
        self.toggle_simulation.setObjectName("toggle_simulation")
        self.horizontalLayout.addWidget(self.toggle_simulation)
        self.reset_simulation = QtGui.QPushButton(self.groupBox)
        self.reset_simulation.setObjectName("reset_simulation")
        self.horizontalLayout.addWidget(self.reset_simulation)
        self.sim_time_slider = QtGui.QSlider(self.groupBox)
        self.sim_time_slider.setMinimum(1)
        self.sim_time_slider.setMaximum(3)
        self.sim_time_slider.setPageStep(1)
        self.sim_time_slider.setOrientation(QtCore.Qt.Horizontal)
        self.sim_time_slider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.sim_time_slider.setTickInterval(1)
        self.sim_time_slider.setObjectName("sim_time_slider")
        self.horizontalLayout.addWidget(self.sim_time_slider)
        self.sim_time_label = QtGui.QLabel(self.groupBox)
        self.sim_time_label.setMaximumSize(QtCore.QSize(16777215, 24))
        self.sim_time_label.setObjectName("sim_time_label")
        self.horizontalLayout.addWidget(self.sim_time_label)
        self.toolButton = QtGui.QToolButton(self.groupBox)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 2, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(400, 284))
        self.groupBox_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.left_wheel_spinbox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.left_wheel_spinbox.setDecimals(6)
        self.left_wheel_spinbox.setMinimum(-10.0)
        self.left_wheel_spinbox.setMaximum(10.0)
        self.left_wheel_spinbox.setSingleStep(0.1)
        self.left_wheel_spinbox.setObjectName("left_wheel_spinbox")
        self.verticalLayout.addWidget(self.left_wheel_spinbox)
        self.left_wheel_slider = QtGui.QSlider(self.groupBox_2)
        self.left_wheel_slider.setMinimum(-10)
        self.left_wheel_slider.setMaximum(10)
        self.left_wheel_slider.setOrientation(QtCore.Qt.Horizontal)
        self.left_wheel_slider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.left_wheel_slider.setTickInterval(1)
        self.left_wheel_slider.setObjectName("left_wheel_slider")
        self.verticalLayout.addWidget(self.left_wheel_slider)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.right_wheel_spinbox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.right_wheel_spinbox.setDecimals(6)
        self.right_wheel_spinbox.setMinimum(-10.0)
        self.right_wheel_spinbox.setMaximum(10.0)
        self.right_wheel_spinbox.setSingleStep(0.1)
        self.right_wheel_spinbox.setObjectName("right_wheel_spinbox")
        self.verticalLayout.addWidget(self.right_wheel_spinbox)
        self.right_wheel_slider = QtGui.QSlider(self.groupBox_2)
        self.right_wheel_slider.setMinimum(-10)
        self.right_wheel_slider.setMaximum(10)
        self.right_wheel_slider.setOrientation(QtCore.Qt.Horizontal)
        self.right_wheel_slider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.right_wheel_slider.setTickInterval(1)
        self.right_wheel_slider.setObjectName("right_wheel_slider")
        self.verticalLayout.addWidget(self.right_wheel_slider)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(400, 284))
        self.groupBox_3.setMaximumSize(QtCore.QSize(400, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.linear_velocity_spinbox = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.linear_velocity_spinbox.setDecimals(6)
        self.linear_velocity_spinbox.setMinimum(-10.0)
        self.linear_velocity_spinbox.setMaximum(10.0)
        self.linear_velocity_spinbox.setSingleStep(0.1)
        self.linear_velocity_spinbox.setObjectName("linear_velocity_spinbox")
        self.verticalLayout_3.addWidget(self.linear_velocity_spinbox)
        self.linear_velocity_slider = QtGui.QSlider(self.groupBox_3)
        self.linear_velocity_slider.setMinimum(-10)
        self.linear_velocity_slider.setMaximum(10)
        self.linear_velocity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.linear_velocity_slider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.linear_velocity_slider.setTickInterval(1)
        self.linear_velocity_slider.setObjectName("linear_velocity_slider")
        self.verticalLayout_3.addWidget(self.linear_velocity_slider)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.angular_velocity_spinbox = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.angular_velocity_spinbox.setDecimals(6)
        self.angular_velocity_spinbox.setMinimum(-10.0)
        self.angular_velocity_spinbox.setMaximum(10.0)
        self.angular_velocity_spinbox.setSingleStep(0.1)
        self.angular_velocity_spinbox.setObjectName("angular_velocity_spinbox")
        self.verticalLayout_3.addWidget(self.angular_velocity_spinbox)
        self.angular_velocity_slider = QtGui.QSlider(self.groupBox_3)
        self.angular_velocity_slider.setMinimum(-10)
        self.angular_velocity_slider.setMaximum(10)
        self.angular_velocity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.angular_velocity_slider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.angular_velocity_slider.setTickInterval(1)
        self.angular_velocity_slider.setObjectName("angular_velocity_slider")
        self.verticalLayout_3.addWidget(self.angular_velocity_slider)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.gridLayout.addWidget(self.groupBox_3, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.toggle_simulation.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.reset_simulation.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.sim_time_label.setText(QtGui.QApplication.translate("MainWindow", "5 Sim Steps per Second", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "Graph...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Forward Kinematics", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Left Wheel Speed (rev/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Right Wheel Speed (rev/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Inverse Kinematics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Linear Velocity (m/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Angular Velocity (rad/s)", None, QtGui.QApplication.UnicodeUTF8))

from renderarea import RenderArea
